
import type { Metadata } from 'next';
import './globals.css';
import { Header } from '@/components/shared/Header';
import { Footer } from '@/components/shared/Footer';
import { Navbar } from '@/components/shared/Navbar';


export const metadata: Metadata = {
  title: 'Be Baby e-commerce',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <div className='divide-y-[1px] divide-foreground/10'>
          <Header />
          <Navbar />
        </div>
        <main className=''>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
